Setup and mobile first PR
MudasirSherwani/Portfolio pull request #1
Opened 2022-08-17 19:25 UTC by MudasirSherwani

### Setup and Mobile First Branch

1. Install Linters
2. Add Index.html file
  - Header with nav bar
  - headline section
3. Add styles.css file
4. Add Readme file

2022-08-17 19:39 UTC, Ismailco requested changes
### Hi @MudasirSherwani, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 19:39 UTC, Ismailco commented on README.md
> +
- [ ] Kindly remove unused headers in your README, so it looks more professional

2022-08-17 19:39 UTC, Ismailco commented on index.html
> +</body>
- [ ] You need to finish the header section by adding the social links and other lists, kindly consider adding this to your page

![Screenshot_20220817_203712](https://user-images.githubusercontent.com/25227022/185227806-f60d8008-46c2-4b0c-96c7-7a43d5585bdf.png)

2022-08-18 06:51 UTC, mgmediaweb approved these changes
Hi @MudasirSherwani, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/41912912/185319490-bb0a5298-610c-4ad0-8853-13dbcc8df5c2.gif)

## Highlights 💯 
- Very well following the suggestions of the previous reviewer.

## Optional suggestions

 [OPTIONAL] I kindly inform you that the previous reviewer overlooked that the white spots of the design should be background images and not floating div, it is highly recommended that you make that change so as not to have problems in future projects that you present, good luck! 🔥 🔥 🔥 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 07:20 UTC, merged