Finish mobile version
MudasirSherwani/Portfolio pull request #2
Opened 2022-08-18 17:59 UTC by MudasirSherwani

Add Work Section

2022-08-18 18:37 UTC, vickymarz requested changes
Hi @MudasirSherwani, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 18:37 UTC, vickymarz commented on index.html
> +      <div class="grid-item proj-4">
- [ ] Good job using flexbox to align your project contents 👍🏼 . Your project cards are currently not centralized or centered on the page as they are all aligned to the left. Kindly align the project elements to the center with equal margin to match the Figma design template you chose 😄 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/185467986-eb1e4c9c-6bc7-4b7a-a71c-a9e1a92d53a8.png)  | ![image](https://user-images.githubusercontent.com/63473584/185468291-0a44285b-8d71-4ff7-8489-6c9f2a2bd957.png)  |

2022-08-18 18:37 UTC, vickymarz commented on index.html
> +          </ul>
- [ ] Kindly ensure you centralize your list of technologies with the appropriate margin as specified in the Figma template you chose👍🏼 

| Figma Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/63473584/185468739-c40603a7-8331-439d-bd55-41cf94373e86.png)  | ![image](https://user-images.githubusercontent.com/63473584/185468894-0c95ec33-a3c9-46ce-bb2e-4f9bd6641fe5.png)  |

2022-08-19 07:59 UTC, sumairq approved these changes
### Hi @MudasirSherwani  , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 10:24 UTC, merged